name: Android (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: |
        cd armorpaint
        ../armorcore/Kinc/make --from ../armorcore android -g opengl
